CREATE TABLE tasks(
	id SERIAL PRIMARY KEY,
	userId INT REFERENCES users(id) NOT NULL,
	startAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	doneAt TIMESTAMP,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	description VARCHAR(80) NOT NULL,
	done BOOLEAN DEFAULT false
);