CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	email VARCHAR(200) NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(80) NOT NULL,
	admin BOOLEAN NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);